// Generated by Wrangler on Fri May 17 2024 14:52:06 GMT+0300 (Israel Daylight Time)
// by running `wrangler types --env-interface Env`

export {};
declare global {
	const BOT_INFO: "{\"id\":6998636845,\"is_bot\":true,\"first_name\":\"DoctorNotifier\",\"username\":\"doctornotifier_bot\",\"can_join_groups\":true,\"can_read_all_group_messages\":false,\"supports_inline_queries\":false,\"can_connect_to_business\":false}";
	const DB: D1Database;
}
