#:schema node_modules/wrangler/config-schema.json
name = "doctor-notifier-worker"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[vars]
BOT_INFO = "{\"id\":6998636845,\"is_bot\":true,\"first_name\":\"DoctorNotifier\",\"username\":\"doctornotifier_bot\",\"can_join_groups\":true,\"can_read_all_group_messages\":false,\"supports_inline_queries\":false,\"can_connect_to_business\":false}"

[[d1_databases]]
binding = "DB"
database_name = "doctor-notifier"
database_id = "85d6beac-e8a5-45b0-a062-8cf297361e56"